insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('1', 'Sukumar', '45', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('2', 'Rob Cohen', '52', '15');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('3', 'Christopher Nolan', '47', '20');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('4', 'Emily Ting', '34', '5');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('5', 'Jeethu Joseph', '50', '8');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('6', 'Alfonso Cuarón', '59', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('7', 'Céline Sciamma', '41', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('8', 'Ryūsuke Hamaguchi', '43', '7');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('9', 'Bong Joon-ho', '49', '15');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('10', 'George Miller', '66', '25');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('11', 'Andy Muschietti', '41', '6');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('12', 'Judd Apatow', '38', '9');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('13', 'Glenn Ficarra', '46', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('14', 'Denis Villeneuve', '57', '18');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('15', 'Patty Jenkins', '45', '14');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('16', 'Dan Trachtenberg', '42', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('17', 'Severin Fiala', '44', '8');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('18', 'Max Barbakow', '36', '13');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('19', 'Michael Showalter', '48', '17');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('20', 'The Wachowskis', '54', '19');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('21', 'James Franco', '55', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('22', 'Ari Aster', '49', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('23', 'Olivia Wilde', '52', '13');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('24', 'Anthony Russo', '46', '16');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('25', 'Joe Russo', '44', '14');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('26', 'John Krasinski', '48', '9');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('27', 'Brad Bird', '50', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('28', 'Nick Cassavetes', '42', '7');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('29', 'George Lucas', '55', '15');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('30', 'Ryan Coogler', '43', '13');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('31', 'Chris Buck', '59', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('32', 'Jennifer Lee', '37', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('33', 'P. Vasu', '51', '8');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('34', 'Abhinav Sunder Nayak', '42', '20');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('35', 'Chandoo Mondeti', '53', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('36', 'Imtiaz Ali', '56', '17');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('37', 'S. Ravi Kumar', '44', '9');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('38', 'Rohith', '48', '15');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('39', 'The Duffer Brothers', '47', '18');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('40', 'Lauren Schmidt Hissrich', '39', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('41', 'Álex Pina', '49', '14');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('42', 'Chris Van Dusen', '43', '17');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('43', 'Peter Morgan', '45', '9');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('44', 'José Padilha', '55', '15');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('45', 'Steve Blackman', '48', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('46', 'Bill Dubuque', '49', '14');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('47', 'Mark Williams', '50', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('48', 'Hwang Dong-hyuk', '43', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('49', 'Eric Goode', '47', '7');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('50', 'Rebecca Chaiklin', '41', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('51', 'Raj Nidimoru', '46', '19');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('52', 'Krishna D.K.', '45', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('53', 'Armando Bó', '42', '8');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('54', 'Avinash Arun', '48', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('55', 'Prosit Roy', '38', '14');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('56', 'Michele Alhaique', '53', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('57', 'Sam Levinson', '50', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('58', 'Craig Mazin', '54', '7');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('59', 'Jonathan Nolan', '44', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('60', 'Lisa Joy', '44', '13');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('61', 'Lucia Aniello', '46', '8');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('62', 'Paul W. Downs', '52', '14');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('63', 'Jen Statsky', '48', '18');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('64', 'Bill Hader', '49', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('65', 'Craig Zobel', '39', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('66', 'Damon Lindelof', '45', '17');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('67', 'Bruce Miller', '50', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('68', 'Steve Martin', '53', '13');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('69', 'John Hoffman', '48', '14');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('70', 'Christopher Storer', '44', '15');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('71', 'Sam Shaw', '45', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('72', 'Dustin Thomason', '48', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('73', 'Ramy Youssef', '53', '13');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('74', 'Maya Erskine', '49', '9');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('75', 'Anna Konkle', '44', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('76', 'Justin Roiland', '52', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('77', 'Mike McMahan', '38', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('78', 'Lindy West', '46', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('79', 'Ali Rushfield', '45', '8');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('80', 'Jon Favreau', '51', '17');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('81', 'Matt Shakman', '53', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('82', 'Michael Waldron', '46', '13');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('83', 'Kari Skogland', '42', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('84', 'Brad Rau', '48', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('85', 'Robert Rodriguez', '44', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('86', 'Tim Federle', '40', '14');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('87', 'Radhakrishnan Parthiban', '53', '15');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('88', 'Sasikanth', '45', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('89', 'Ryan White', '50', '9');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('90', 'Tia Lessin', '48', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('91', 'Emma Pildes', '52', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('92', 'Sara Dosa', '46', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('93', 'Felicity Morris', '42', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('94', 'Ahmir "Questlove" Thompson', '48', '8');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('95', 'Laura McGann', '44', '17');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('96', 'Daniel Roher', '55', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('97', 'Jeff Orlowski', '40', '13');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('98', 'Pippa Ehrlich', '53', '11');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('99', 'James Reed', '45', '10');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('100', 'Peter Jackson', '47', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('101', 'Tim Wardle', '55', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('102', 'Rob Miller', '50', '12');
insert into Director (ID,Director_name, Age, Total_number_of_directions) values ('103', 'Joshua Oppenheimer', '61', '6');
